# Generated by Django 4.0 on 2022-01-22 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0002_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='destino', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='origen', to='auth.user'),
        ),
    ]
